### ISSUE TITLE
Error: socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by zone-b** [ostrolucky/Bulk-Bing-Image-downloader#33]
I get an error from the socket when invoking

```
python bbid.py -s "Hello World" -o Test

Traceback (most recent call last):
  File "bbid.py", line 134, in <module>
    fetch_images_from_keyword(pool_sema, args.search_string,output_dir, args.filters, args.limit)
  File "bbid.py", line 72, in fetch_images_from_keyword
    html = response.read().decode('utf8')
  File "C:\Tools\Anaconda3\envs\github\lib\http\client.py", line 471, in read
    s = self._safe_read(self.length)
  File "C:\Tools\Anaconda3\envs\github\lib\http\client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "C:\Tools\Anaconda3\envs\github\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Tools\Anaconda3\envs\github\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Tools\Anaconda3\envs\github\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

Internet connection works, changed user agent, timeout etc. without effort. Any ideas?

**Comment by ostrolucky** [comment]
This project was tested on lot of windows machines. Unless somebody reports the actual bug in my code, I'll have to flag this as an issue in your network or pc settings, sorry.
